name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/reports/tests

    - name: Upload build results
      uses: actions/upload-artifact@v2
      with:
        name: build-results
        path: build/reports

    - name: Upload jar
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: build/libs

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: build/reports/jacoco/test/html

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs
